combiner:
  activation: relu
  dropout: false
  fc_layers: null
  fc_size: 128
  initializer: null
  norm: null
  num_fc_layers: 1
  regularization_lambda: 0.01
  regularize: true
  type: concat
input_features:
- name: FEATURE_0
  type: numerical
- name: FEATURE_1
  type: category
- name: FEATURE_2
  type: numerical
- name: FEATURE_3
  type: numerical
- name: FEATURE_4
  type: numerical
- name: FEATURE_5
  type: numerical
- name: FEATURE_6
  type: numerical
- name: FEATURE_7
  type: numerical
- name: FEATURE_8
  type: numerical
- name: FEATURE_9
  type: numerical
- name: FEATURE_10
  type: numerical
- name: FEATURE_11
  type: numerical
- name: FEATURE_12
  type: numerical
- name: FEATURE_13
  type: numerical
- name: FEATURE_14
  type: numerical
- name: FEATURE_15
  type: numerical
- name: FEATURE_16
  type: numerical
- name: FEATURE_17
  type: numerical
- name: FEATURE_18
  type: numerical
- name: FEATURE_19
  type: numerical
- name: FEATURE_20
  type: numerical
- name: FEATURE_21
  type: numerical
- name: FEATURE_22
  type: numerical
- name: FEATURE_23
  type: numerical
- name: FEATURE_24
  type: numerical
- name: FEATURE_25
  type: numerical
- name: FEATURE_26
  type: numerical
- name: FEATURE_27
  type: numerical
- name: FEATURE_28
  type: numerical
- name: FEATURE_29
  type: numerical
- name: FEATURE_30
  type: numerical
- name: FEATURE_31
  type: numerical
- name: FEATURE_32
  type: numerical
- name: FEATURE_33
  type: numerical
- name: FEATURE_34
  type: numerical
- name: FEATURE_35
  type: numerical
- name: FEATURE_36
  type: numerical
- name: FEATURE_37
  type: numerical
- name: FEATURE_38
  type: numerical
- name: FEATURE_39
  type: numerical
- name: FEATURE_40
  type: numerical
- name: FEATURE_41
  type: numerical
- name: FEATURE_42
  type: numerical
- name: FEATURE_43
  type: numerical
- name: FEATURE_44
  type: numerical
- name: FEATURE_45
  type: numerical
- name: FEATURE_46
  type: numerical
- name: FEATURE_47
  type: numerical
- name: FEATURE_48
  type: numerical
- name: FEATURE_49
  type: numerical
- name: FEATURE_50
  type: numerical
- name: FEATURE_51
  type: numerical
- name: FEATURE_52
  type: numerical
- name: FEATURE_53
  type: numerical
- name: FEATURE_54
  type: numerical
- name: FEATURE_55
  type: numerical
- name: FEATURE_56
  type: numerical
- name: FEATURE_57
  type: numerical
- name: FEATURE_58
  type: numerical
- name: FEATURE_59
  type: numerical
- name: FEATURE_60
  type: numerical
- name: FEATURE_61
  type: numerical
- name: FEATURE_62
  type: numerical
- name: FEATURE_63
  type: numerical
- name: FEATURE_64
  type: numerical
- name: FEATURE_65
  type: numerical
- name: FEATURE_66
  type: numerical
- name: FEATURE_67
  type: numerical
- name: FEATURE_68
  type: numerical
- name: FEATURE_69
  type: numerical
- name: FEATURE_70
  type: numerical
- name: FEATURE_71
  type: numerical
- name: FEATURE_72
  type: numerical
- name: FEATURE_73
  type: numerical
- name: FEATURE_74
  type: numerical
- name: FEATURE_75
  type: numerical
- name: FEATURE_76
  type: numerical
- name: FEATURE_77
  type: numerical
- name: FEATURE_78
  type: numerical
- name: FEATURE_79
  type: numerical
- name: FEATURE_80
  type: numerical
- name: FEATURE_81
  type: numerical
- name: FEATURE_82
  type: numerical
- name: FEATURE_83
  type: numerical
- name: FEATURE_84
  type: numerical
- name: FEATURE_85
  type: numerical
- name: FEATURE_86
  type: numerical
- name: FEATURE_87
  type: numerical
- name: FEATURE_88
  type: numerical
- name: FEATURE_89
  type: numerical
- name: FEATURE_90
  type: numerical
- name: FEATURE_91
  type: numerical
- name: FEATURE_92
  type: numerical
- name: FEATURE_93
  type: numerical
- name: FEATURE_94
  type: numerical
- name: FEATURE_95
  type: numerical
- name: FEATURE_96
  type: numerical
- name: FEATURE_97
  type: numerical
- name: FEATURE_98
  type: numerical
- name: FEATURE_99
  type: numerical
- name: FEATURE_100
  type: numerical
- name: FEATURE_101
  type: numerical
- name: FEATURE_102
  type: numerical
- name: FEATURE_103
  type: numerical
- name: FEATURE_104
  type: numerical
- name: FEATURE_105
  type: numerical
- name: FEATURE_106
  type: numerical
- name: FEATURE_107
  type: numerical
- name: FEATURE_108
  type: numerical
- name: FEATURE_109
  type: numerical
- name: FEATURE_110
  type: numerical
- name: FEATURE_111
  type: numerical
- name: FEATURE_112
  type: numerical
- name: FEATURE_113
  type: numerical
- name: FEATURE_114
  type: numerical
- name: FEATURE_115
  type: numerical
- name: FEATURE_116
  type: numerical
- name: FEATURE_117
  type: numerical
- name: FEATURE_118
  type: numerical
- name: FEATURE_119
  type: numerical
- name: FEATURE_120
  type: numerical
- name: FEATURE_121
  type: numerical
- name: FEATURE_122
  type: category
- name: FEATURE_123
  type: numerical
- name: FEATURE_124
  type: numerical
- name: FEATURE_125
  type: numerical
- name: FEATURE_126
  type: numerical
- name: FEATURE_127
  type: numerical
- name: FEATURE_128
  type: numerical
- name: FEATURE_129
  type: numerical
- name: FEATURE_130
  type: numerical
- name: FEATURE_131
  type: numerical
- name: FEATURE_132
  type: numerical
- name: FEATURE_133
  type: numerical
- name: FEATURE_134
  type: numerical
- name: FEATURE_135
  type: numerical
- name: FEATURE_136
  type: numerical
- name: FEATURE_137
  type: numerical
- name: FEATURE_138
  type: numerical
- name: FEATURE_139
  type: numerical
- name: FEATURE_140
  type: numerical
- name: FEATURE_141
  type: numerical
- name: FEATURE_142
  type: numerical
- name: FEATURE_143
  type: numerical
- name: FEATURE_144
  type: numerical
- name: FEATURE_145
  type: numerical
- name: FEATURE_146
  type: numerical
- name: FEATURE_147
  type: numerical
- name: FEATURE_148
  type: numerical
- name: FEATURE_149
  type: numerical
- name: FEATURE_150
  type: numerical
- name: FEATURE_151
  type: numerical
- name: FEATURE_152
  type: numerical
- name: FEATURE_153
  type: numerical
- name: FEATURE_154
  type: numerical
- name: FEATURE_155
  type: numerical
- name: FEATURE_156
  type: numerical
- name: FEATURE_157
  type: numerical
- name: FEATURE_158
  type: numerical
- name: FEATURE_159
  type: numerical
- name: FEATURE_160
  type: numerical
- name: FEATURE_161
  type: numerical
- name: FEATURE_162
  type: numerical
- name: FEATURE_163
  type: numerical
- name: FEATURE_164
  type: numerical
- name: FEATURE_165
  type: numerical
- name: FEATURE_166
  type: numerical
- name: FEATURE_167
  type: numerical
- name: FEATURE_168
  type: numerical
- name: FEATURE_169
  type: numerical
- name: FEATURE_170
  type: numerical
- name: FEATURE_171
  type: numerical
- name: FEATURE_172
  type: numerical
- name: FEATURE_173
  type: numerical
- name: FEATURE_174
  type: numerical
- name: FEATURE_175
  type: numerical
- name: FEATURE_176
  type: numerical
- name: FEATURE_177
  type: numerical
- name: FEATURE_178
  type: numerical
- name: FEATURE_179
  type: numerical
- name: FEATURE_180
  type: numerical
- name: FEATURE_181
  type: numerical
- name: FEATURE_182
  type: numerical
- name: FEATURE_183
  type: numerical
- name: FEATURE_184
  type: numerical
- name: FEATURE_185
  type: numerical
- name: FEATURE_186
  type: numerical
- name: FEATURE_187
  type: numerical
- name: FEATURE_188
  type: numerical
- name: FEATURE_189
  type: numerical
- name: FEATURE_190
  type: numerical
- name: FEATURE_191
  type: numerical
- name: FEATURE_192
  type: numerical
- name: FEATURE_193
  type: numerical
- name: FEATURE_194
  type: numerical
- name: FEATURE_195
  type: numerical
- name: FEATURE_196
  type: numerical
- name: FEATURE_197
  type: numerical
- name: FEATURE_198
  type: numerical
- name: FEATURE_199
  type: numerical
- name: FEATURE_200
  type: numerical
- name: FEATURE_201
  type: numerical
- name: FEATURE_202
  type: numerical
- name: FEATURE_203
  type: numerical
- name: FEATURE_204
  type: numerical
- name: FEATURE_205
  type: numerical
- name: FEATURE_206
  type: numerical
- name: FEATURE_207
  type: numerical
- name: FEATURE_208
  type: numerical
- name: FEATURE_209
  type: numerical
- name: FEATURE_210
  type: numerical
- name: FEATURE_211
  type: numerical
- name: FEATURE_212
  type: numerical
- name: FEATURE_213
  type: numerical
- name: FEATURE_214
  type: numerical
- name: FEATURE_215
  type: numerical
- name: FEATURE_216
  type: numerical
- name: FEATURE_217
  type: numerical
- name: FEATURE_218
  type: numerical
- name: FEATURE_219
  type: numerical
- name: FEATURE_220
  type: numerical
- name: FEATURE_221
  type: numerical
- name: FEATURE_222
  type: numerical
- name: FEATURE_223
  type: numerical
- name: FEATURE_224
  type: numerical
- name: FEATURE_225
  type: numerical
- name: FEATURE_226
  type: numerical
- name: FEATURE_227
  type: numerical
- name: FEATURE_228
  type: numerical
- name: FEATURE_229
  type: numerical
- name: FEATURE_230
  type: numerical
- name: FEATURE_231
  type: numerical
- name: FEATURE_232
  type: numerical
- name: FEATURE_233
  type: numerical
- name: FEATURE_234
  type: numerical
- name: FEATURE_235
  type: numerical
- name: FEATURE_236
  type: numerical
- name: FEATURE_237
  type: numerical
- name: FEATURE_238
  type: numerical
- name: FEATURE_239
  type: numerical
- name: FEATURE_240
  type: numerical
- name: FEATURE_241
  type: numerical
- name: FEATURE_242
  type: numerical
- name: FEATURE_243
  type: numerical
- name: FEATURE_244
  type: numerical
- name: FEATURE_245
  type: numerical
- name: FEATURE_246
  type: numerical
- name: FEATURE_247
  type: numerical
- name: FEATURE_248
  type: numerical
- name: FEATURE_249
  type: numerical
- name: FEATURE_250
  type: numerical
- name: FEATURE_251
  type: numerical
- name: FEATURE_252
  type: numerical
- name: FEATURE_253
  type: numerical
- name: FEATURE_254
  type: numerical
- name: FEATURE_255
  type: numerical
- name: FEATURE_256
  type: numerical
- name: FEATURE_257
  type: numerical
- name: FEATURE_258
  type: numerical
- name: FEATURE_259
  type: numerical
- name: FEATURE_260
  type: numerical
- name: FEATURE_261
  type: numerical
- name: FEATURE_262
  type: numerical
- name: FEATURE_263
  type: numerical
- name: FEATURE_264
  type: numerical
- name: FEATURE_265
  type: numerical
- name: FEATURE_266
  type: numerical
- name: FEATURE_267
  type: numerical
- name: FEATURE_268
  type: numerical
- name: FEATURE_269
  type: numerical
- name: FEATURE_270
  type: numerical
- name: FEATURE_271
  type: numerical
- name: FEATURE_272
  type: numerical
- name: FEATURE_273
  type: numerical
- name: FEATURE_274
  type: numerical
- name: FEATURE_275
  type: numerical
- name: FEATURE_276
  type: numerical
- name: FEATURE_277
  type: numerical
- name: FEATURE_278
  type: numerical
- name: FEATURE_279
  type: numerical
- name: FEATURE_280
  type: numerical
- name: FEATURE_281
  type: numerical
- name: FEATURE_282
  type: numerical
- name: FEATURE_283
  type: numerical
- name: FEATURE_284
  type: numerical
- name: FEATURE_285
  type: numerical
- name: FEATURE_286
  type: numerical
- name: FEATURE_287
  type: numerical
- name: FEATURE_288
  type: numerical
- name: FEATURE_289
  type: numerical
- name: FEATURE_290
  type: numerical
- name: FEATURE_291
  type: numerical
- name: FEATURE_292
  type: numerical
- name: FEATURE_293
  type: numerical
- name: FEATURE_294
  type: numerical
- name: FEATURE_295
  type: numerical
- name: FEATURE_296
  type: numerical
- name: FEATURE_297
  type: numerical
- name: FEATURE_298
  type: numerical
- name: FEATURE_299
  type: numerical
- name: FEATURE_300
  type: numerical
- name: FEATURE_301
  type: numerical
- name: FEATURE_302
  type: numerical
- name: FEATURE_303
  type: numerical
- name: FEATURE_304
  type: numerical
- name: FEATURE_305
  type: numerical
- name: FEATURE_306
  type: numerical
- name: FEATURE_307
  type: numerical
- name: FEATURE_308
  type: numerical
- name: FEATURE_309
  type: numerical
- name: FEATURE_310
  type: numerical
- name: FEATURE_311
  type: numerical
- name: FEATURE_312
  type: numerical
- name: FEATURE_313
  type: numerical
- name: FEATURE_314
  type: numerical
- name: FEATURE_315
  type: numerical
- name: FEATURE_316
  type: numerical
- name: FEATURE_317
  type: numerical
- name: FEATURE_318
  type: numerical
- name: FEATURE_319
  type: numerical
- name: FEATURE_320
  type: numerical
- name: FEATURE_321
  type: numerical
- name: FEATURE_322
  type: numerical
- name: FEATURE_323
  type: numerical
- name: FEATURE_324
  type: numerical
- name: FEATURE_325
  type: numerical
- name: FEATURE_326
  type: numerical
- name: FEATURE_327
  type: numerical
- name: FEATURE_328
  type: numerical
- name: FEATURE_329
  type: numerical
- name: FEATURE_330
  type: numerical
- name: FEATURE_331
  type: numerical
- name: FEATURE_332
  type: numerical
- name: FEATURE_333
  type: numerical
- name: FEATURE_334
  type: numerical
- name: FEATURE_335
  type: numerical
- name: FEATURE_336
  type: numerical
- name: FEATURE_337
  type: numerical
- name: FEATURE_338
  type: numerical
- name: FEATURE_339
  type: numerical
- name: FEATURE_340
  type: numerical
- name: FEATURE_341
  type: numerical
- name: FEATURE_342
  type: numerical
- name: FEATURE_343
  type: numerical
- name: FEATURE_344
  type: numerical
- name: FEATURE_345
  type: numerical
- name: FEATURE_346
  type: numerical
- name: FEATURE_347
  type: numerical
- name: FEATURE_348
  type: numerical
- name: FEATURE_349
  type: numerical
- name: FEATURE_350
  type: numerical
- name: FEATURE_351
  type: numerical
- name: FEATURE_352
  type: numerical
- name: FEATURE_353
  type: numerical
- name: FEATURE_354
  type: numerical
- name: FEATURE_355
  type: numerical
output_features:
- loss:
    class_weights:
    - 0
    - 1.0
    - 1.0833078828599545
    - 1.0980634953393182
    weight: 1
  name: CATEGORY_PREDICTOR_0
  type: category
- loss:
    class_weights:
    - 0
    - 1.0
    - 1.0094265633012578
    - 1.4029935224199737
    weight: 1
  name: CATEGORY_PREDICTOR_1
  type: category
- loss:
    class_weights:
    - 0
    - 1.0
    - 1.0058962937582092
    - 1.7426479681432565
    weight: 1
  name: CATEGORY_PREDICTOR_2
  type: category
- loss:
    class_weights:
    - 0
    - 1.0
    - 1.0052961775123366
    - 2.407427004665929
    weight: 1
  name: CATEGORY_PREDICTOR_3
  type: category
training:
  batch_size: 32
  decay: true
  early_stop: 5
  epochs: 100
  learning_rate: 1.0e-05
  regularization_lambda: 0.001
  regularize: true
  validation_field: combined
  validation_measure: loss
